replicaCount: 2

image:
  repository: davitmadoyan/trg-task
  tag: "1.0.9"
  pullPolicy: IfNotPresent

service:
  name: myapp-service
  type: ClusterIP
  port: 8085
  targetPort: 8085

env:
  name: dev
